document.write('<header class="navbar" id="header-navbar">');
document.write('<div class="container">');
document.write('<a href="../Administracion_Usuario_Grupo/viewPerfil.html" id="logo" class="navbar-brand col-md-3 col-sm-4 col-xs-12">');
document.write('<img src="../../template/img/logo.png" alt=""/> ProCal-ProSer</a>');
document.write('<button class="navbar-toggle" data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button">');
document.write('<span class="sr-only">Toggle navigation</span>');
document.write('<span class="fa fa-bars"></span>');
document.write('</button>');
document.write('<div class="nav-no-collapse pull-right" id="header-nav">');
document.write('<ul class="nav navbar-nav pull-right">');
document.write('<li class="mobile-search">');
document.write('<a class="btn"><i class="fa fa-search"></i></a>');
document.write('<div class="drowdown-search">');
document.write('<div class="form-group">');
document.write('<input id="criterioBusqueda" type="text" class="form-control" placeholder="Búsqueda básica...">');
document.write('<i class="fa fa-search nav-search-icon"></i>');
document.write('</div>');
document.write('</div>');						
document.write('</li>');
document.write('<li class="dropdown hidden-xs">');
document.write('<a class="btn dropdown-toggle" data-toggle="dropdown"><i class="fa fa-cog"></i></a>');
document.write('<ul class="dropdown-menu">');
//document.write('<li><a href="../Busqueda/ViewBusquedaAvanzada.html"><i class="fa fa-search"></i>Búsqueda Avanzada</a></li>');
//document.write('<li><a href="../Publicacion_Documental/ViewBusquedaAsistida.html"><i class="fa fa-search-plus"></i>Búsqueda Asistida</a></li>');
document.write('</ul>');
document.write('<li>');
document.write('<li class="dropdown profile-dropdown">');
document.write('<a href="" class="dropdown-toggle" data-toggle="dropdown">');
document.write('<img src="../../template/img/samples/profile-photo.png" alt=""/>');
document.write('<span class="hidden-xs"></span> <b class="caret"></b></a>');
document.write('<ul class="dropdown-menu">');
document.write('<li><a href="../Administracion_Usuario_Grupo/viewPerfil.html"><i class="fa fa-user"></i>Ver Cuenta</a></li>');
document.write('<li><a href="../Administracion_Usuario_Grupo/ViewModificarPerfil.html"><i class="fa fa-cog"></i>Editar Cuenta</a></li>');
document.write('<li><a id="salir"><i class="fa fa-power-off"></i>Salir</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li class="hidden-xxs"><a id="poweroff" class="btn"><i class="fa fa-power-off"></i></a></li>');
document.write('</ul>');
document.write('</div>');
document.write('</div>');
document.write('</header>');
